name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Copy index.html to dist
        run: |
          mkdir -p dist
          cp index.html dist/

      # 构建 aigc-dev 演示文稿
      - name: Install dependencies for aigc-dev
        run: |
          cd talks/aigc-dev
          nci

      - name: Build aigc-dev
        run: |
          cd talks/aigc-dev
          nr build
          mkdir -p ../../dist/talks/aigc-dev
          cp -r dist/* ../../dist/talks/aigc-dev/

      # 未来可以在这里添加更多演示文稿的构建步骤
      # 例如:
      # - name: Build another-talk
      #   run: |
      #     cd talks/another-talk
      #     nci
      #     nr build
      #     mkdir -p ../../dist/talks/another-talk
      #     cp -r dist/* ../../dist/talks/another-talk/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4